name: Java CI
on: [push]
jobs:
  version:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      - run: git config --global user.name 'Filip-Kaczmarek'
      - run: git config --global user.email 'f.7.kaczmarek@wp.pl'
      - run: npm version patch -m "[RELEASE] %s"
      - run: git push